upd

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,6 +12,26 @@ parameters:
     default: ""
 
 jobs:
+  check_for_failure:
+    executor: python-executor
+    parameters:
+      version:
+        type: string
+        default: ""
+      schema:
+        type: string
+        default: ""
+    steps:
+      - checkout
+      - run:
+          name: Check Last Commit Message for Error Flag
+          command: |
+            LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
+            if [[ "$LAST_COMMIT_MSG" == *"[ci error]"* ]]; then
+              echo "Failing build due to ci error flag in commit message."
+              exit 1
+            fi
+
   take_snapshot:
     executor: python-executor
     parameters:
@@ -77,11 +97,11 @@ jobs:
               git config --global user.name "$GIT_USER_NAME"
               git config --global user.email "$GIT_USER_EMAIL"
               git add diffs/<< parameters.schema >>/schema_diff.sql
-              git commit -m "Found schema differences [ci skip]"
+              git commit -m "Found schema differences [ci error]"
               git push origin $(git rev-parse --abbrev-ref HEAD)
               exit 1
             fi
-      
+
   deploy:
     executor: python-executor
     parameters:
@@ -93,13 +113,8 @@ jobs:
         default: ""
     steps:
       - checkout
-      # - attach_workspace:
-      #     at: .
       - setup_remote_docker:
           version: default
-      # - add_ssh_keys:
-      #     fingerprints:
-      #       - "mpwb+fo8b0vSe3cC4/2yEp1GBc6908FGNp/XYj6rJMA"
       - run:
           name: Install dependencies
           command: |
@@ -139,28 +154,18 @@ jobs:
             git status
             git commit -m "Updated plan files and schema snapshot [ci skip]"
             git push origin $(git rev-parse --abbrev-ref HEAD)
-      # - run:
-      #     name: Debug and Push changes
-      #     command: |
-      #       echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
-      #       echo "Git status:"
-      #       git status
-      #       echo "Pushing changes..."
-      #       git push origin $(git rev-parse --abbrev-ref HEAD)
-      # - run:
-      #     name: Clean Repository
-      #     command: |
-      #       ls
-      #       rm -rf diffs
-      #       rm -rf snapshots/<< parameters.schema >>
-      #       git commit -am "Clean up after deployment [ci skip]"
-      #       git push origin $(git rev-parse --abbrev-ref HEAD)
+
 
 workflows:
   version: 2
   deploy_on_tag:
     jobs:
+      - check_for_failure:
+          schema: platform
+          context: cicd
       - take_snapshot:
+          requires:
+            - check_for_failure
           schema: platform
           context: cicd
       - compare_schemas:
@@ -172,16 +177,8 @@ workflows:
           requires:
             - compare_schemas
           filters:
-          #   branches:
-          #     only: master
             tags:
               only: /^v.*/
           version: v0.1.1
           schema: platform
           context: cicd
-      # - commit_and_push:
-      #     requires:
-      #       - deploy
-      #     filters:
-      #       tags:
-      #         only: /^v.*/
