upd

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -110,8 +110,12 @@ jobs:
           name: Deploy schemas
           command: |
             . venv/bin/activate
-            tool_deployer -e caiso -a deploy -v "<< parameters.version >>" -st all -sch << parameters.schema >>
-
+            if tool_deployer -e caiso -a deploy -v "<< parameters.git_tag >>" -st all -sch << parameters.schema >> 2>&1 | tee /dev/tty | grep -q 'ERROR'; then
+              echo "Deployment failed with errors."
+              exit 1
+            else
+              echo "Deployment succeeded."
+            fi
       - run:
           name: Configure git
           command: |
@@ -121,15 +125,6 @@ jobs:
             echo "Mail: $GIT_USER_EMAIL"
             git config --global user.name "$GIT_USER_NAME"
             git config --global user.email "$GIT_USER_EMAIL"
-      - run:
-          name: Check for Errors in Logs
-          command: |
-            if grep -q 'ERROR' tool_deployer.log; then
-              echo "Deployment failed with errors."
-              exit 1
-            else
-              echo "Deployment succeeded."
-            fi
       - run:
           name: Take Post-deployment Snapshot
           command: |
